language: python
python:
  - "3.6.4"
install:
  - pip install -r requirements.txt
script:
  - nosetest test.py
branches:
  only:
  - master
  - develop
  - feature
  - feature_api_logic
 after_success:
  - coveralls